### ISSUE TITLE
String.format bug in SQLServerConnector

### ISSUE THREAD

**Issue by svdwoude** [mitdbg/aurum-datadiscovery#119]
I'd expect Java String formatting  to use `'%s'` as a placeholder instead of `{}`. At least this currently breaks the SQL Server profiling part on our end.  :man_shrugging: 

https://github.com/mitdbg/aurum-datadiscovery/blob/2c873c914956ca40ebfd53ac2f91ac5f635bd7b4/ddprofiler/src/main/java/inputoutput/connectors/SQLServerConnector.java#L90

**Comment by raulcf** [comment]
nice catch. happy to merge a pull request with a fix!
