### ISSUE TITLE
Issue with Matplotlib

### ISSUE THREAD

**Issue by rajscotia** [mitdbg/aurum-datadiscovery#125]
I followed the steps on Readme and installed data discovery, but got the below error when executing the function. 

"from main import init_system
api, reporting = init_system("/opt/dsmi/aurum-datadiscovery/data/model/", reporting=False)"

Error: 

Bad key "lines.dashed_pattern" on line 18 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "date.autoformatter.second" on line 235 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "boxplot.meanprops.markerfacecolor" on line 368 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "ytick.left" on line 258 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "lines.scale_dashes" on line 21 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "ytick.right" on line 259 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "xtick.minor.bottom" on line 256 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "xtick.major.top" on line 253 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "date.autoformatter.minute" on line 234 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "lines.dashdot_pattern" on line 19 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "lines.dotted_pattern" on line 20 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "date.autoformatter.year" on line 230 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "ytick.major.left" on line 270 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "hatch.linewidth" on line 38 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "axes.titlepad" on line 184 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "hist.bins" on line 40 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "ytick.major.right" on line 271 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "date.autoformatter.hour" on line 233 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "boxplot.meanprops.marker" on line 367 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "boxplot.meanprops.markersize" on line 370 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "xtick.bottom" on line 242 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "_internal.classic_mode" on line 526 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "hatch.color" on line 37 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "axes.autolimit_mode" on line 220 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "ytick.minor.left" on line 272 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "xtick.major.bottom" on line 254 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "boxplot.meanprops.markeredgecolor" on line 369 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "date.autoformatter.microsecond" on line 236 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "axes.formatter.offset_threshold" on line 207 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "xtick.minor.top" on line 255 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "patch.force_edgecolor" on line 33 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "date.autoformatter.month" on line 231 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "xtick.top" on line 241 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "ytick.minor.right" on line 273 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/__init__.py:1069: UserWarning: Bad val "auto" on line #360
	"boxplot.flierprops.markerfacecolor: auto
"
	in file "/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle"
	Key boxplot.flierprops.markerfacecolor: auto does not look like a color arg
  (val, error_details, msg))

Bad key "date.autoformatter.day" on line 232 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

Bad key "scatter.marker" on line 345 in
/opt/anaconda3/lib/python3.5/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle.
You probably need to get an updated matplotlibrc file from
http://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template
or from the matplotlib source distribution

please help! 

Thanks.

**Comment by suhailshergill** [comment]
For reference the `matplotlib` version installed when this error was encountered was `1.5.1` per requirements file

**Comment by suhailshergill** [comment]
@raulcf could you confirm the `matplotlib` version that we should be using? is the [`requirements.txt`](https://github.com/mitdbg/aurum-datadiscovery/blob/master/requirements.txt) stale by any chance?

**Comment by raulcf** [comment]
It works for me with matplotlib 1.5.1, the version indicated in requirements.txt on a mac and on ubuntu. Are you using a different platform? I wonder if that's what's triggering the error.

**Comment by raulcf** [comment]
Do you have a specific configuration in your matplotlibrc file? Mine only has this:
backend: TkAgg
because I'm running on mac

**Comment by suhailshergill** [comment]
@raulcf we're using a conda environment on redhat/centos. @rajscotia can share details regd `.matplotlibrc` and other packages in the environment

**Comment by rajscotia** [comment]
@raulcf there were some dependency issues with python libraries.... I think we have cleared all of it now.
