### ISSUE TITLE
column similarity scores not stored in Elastic

### ISSUE THREAD

**Issue by RawatVimal** [mitdbg/aurum-datadiscovery#149]
Please correct me if my understanding is not correct. I could manage to run profiler and could see data stored in Elastic also could manage to load pkl objects to neo4J. What I am still missing is coloumn similarity scores. I imagine these scores to be present in Elastic but I am not able to find them. Is this a known issue or I am not running aurum correctly ?

**Comment by raulcf** [comment]
The column similarity scores are stored as an edge-attribute in the
networkX graph that is produced by networkbuildercoordinator. They are not
in elasticsearch and instead in the typically pkl file produced by that
module. Hope this helps!

**Comment by RawatVimal** [comment]
thanks. Yes
