### ISSUE TITLE
Duplicating the target Table in join path finder

### ISSUE THREAD

**Issue by qahtanaa** [mitdbg/aurum-datadiscovery#78]
In many cases, the api to find the join path between two tables returns the target tables with two fields such as the following example:

[chembl_22.molecule_frac_classification.mol_frac_id 4086686333 0,
chembl_22.docs.issue 1119713182 1.0,
chembl_22.docs.volume 1864138338 0,
chembl_22.molecule_hrac_classification.hrac_class_id 4194548617 0.9658536585365853,
chembl_22.molecule_hrac_classification.molregno 3916804396 0],

the target table "molecule_hrac_classification" has been returned with two fields "hrac_class_id" and "molregno"

**Comment by raulcf** [comment]
this has now been fixed
